# Generated by Django 4.0.5 on 2022-06-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=200)),
                ('peritemprice', models.CharField(max_length=200)),
                ('totalqty', models.CharField(max_length=200)),
                ('totalprice', models.CharField(max_length=200)),
            ],
        ),
    ]
